# This is a basic workflow to help you get started with Actions
name: Terraform Destroy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # This step saves your AWS access and secret key to be used by Terraform
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.5
    
    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform Destroy
      run: |
        terraform destroy -lock=false -auto-approve
        
    
