# This is a basic workflow to help you get started with Actions
name: Terraform CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    inputs:
      test:
        type: choice
        options:
          - test1
          - test2
  # push:
  #   branches: [master]
  #   paths: ["terraform/**"]

  # pull_request:
  #   branches: [master]
  #   paths: ["terraform/**"]
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # This step saves your AWS access and secret key to be used by Terraform
    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.5
    
    - name: Terraform Init
      run: |
        terraform init
    - name: Terraform Validate
      run: |
        terraform validate

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve -lock=false

    - name: Change Tag back to TAG
      run: |
        sed -i "s/\(image\": \"\${aws_ecr_repository\.app_ecr_repo\.repository_url}:\)[^\"]*/\1TAG/" ./ecs.tf

    - uses: stefanzweifel/git-auto-commit-action@v5
      name: commit changes to Tag

